### ISSUE TITLE
AJAX Experiment : Documentation Missing and Broken images

### ISSUE THREAD

**Issue by rishi11** [BoruiGu/CS5610-borui#2]
1. Documentation for AJAX experiments are missing.

2. There are image tags in page with not proper source.

**Comment by BoruiGu** [comment]
1. Documentation updated, please check
2. 
1>
In html template, 
`<img class="poster" src="http://ia.media-imdb.com/images/M/MV5BMTg0MDQ1OTQ3MF5BMl5BanBnXkFtZTcwODE2MzE2MQ@@._V1_SY317_CR51,0,214,317_AL_.jpg">` I believe this source is valid.<br>
2>
While rendering data retrieved from server, since there are movies without a poster, I added a if statement `if (!movie.urlPoster) continue;` so that now a movie is only rendered if it has a proper poster url.
